[project]
name = "tshet-uinh-py"
version = "0.1.0"
description = "A Python library for the Qieyun phonological system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
include = ["tshet_uinh*"]
exclude = ["prepare", "tests"]
