line-length = 100

[lint]
select = ["F", "E", "W", "UP", "I", "N", "PERF", "D"]
ignore = ["D415", "N999", "N801", "N802", "N803", "N806"]

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[lint.pydocstyle]
convention = "google"

[format]
line-ending = "lf"
docstring-code-format = true
